version: '3.8'
services:
  postgres:
    build: 
      dockerfile: "./db.Dockerfile"
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DATABASE_URL=$DATABASE_URL
    networks: 
      - lib
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '$DB_HOST_PORT:$DB_CONTAINER_PORT'

  app:
    depends_on: 
      - postgres
    build: 
      dockerfile: "./web.Dockerfile"
    restart: on-failure
    env_file: .env
    ports: 
      - '$PORT:$PORT'
    networks: 
      - lib
    volumes:
      - ./:/app
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DATABASE_URL=$DATABASE_URL

networks:
  lib:

volumes:
  postgres:
